#include <stdio.h>
unsigned long long sing(unsigned long long x);
unsigned long long doub(unsigned long long x);
int main()
{
    unsigned long long  x,n;
    int k;
    while(scanf("%llu",&x)!=EOF)
    {
    k=1;
    for(printf("Hailstone generated by %llu:\n%llu ",x,x);x!=1;k++)
	{
        if(x%2) x=sing(x);
        else    x=doub(x);
        printf("%llu ",x);
    }
    putchar('\n');
    printf("Number of hailstone generated:%lu\n\n",k);
    }
}

unsigned long long sing(unsigned long long x)
{
    x=(3*x+1);
    return x;
}
unsigned long long doub(unsigned long long x)
{
    x=(x/2);
    return x;
}
