.386
STACK SEGMENT USE16 STACK
    DB 200 DUP(0)
STACK ENDS
CODE SEGMENT USE16
ASSUME CS:CODE,SS:STACK
OLD_CHAR DW ?,?
NEW16H:
    CMP AH,00H
    JE LTH
    CMP AH,10H
    JE LTH
    JMP DWORD PTR OLD_CHAR
LTH: 
    PUSHF
    CALL DWORD PTR OLD_CHAR
    CMP AL,41H ;小于A退出
    JB QUIT
    CMP AL,5AH ;大于Z退出
    JA QUIT
    ADD AL,20H ;将大写转换为小写
QUIT: 
    IRET
START: 
    XOR AX,AX
    MOV DS,AX
    MOV AX,DS:[16H*4]
    MOV OLD_CHAR,AX
    MOV AX,DS:[16H*4+2]
    MOV OLD_CHAR+2,AX
    CLI
    MOV WORD PTR DS:[16H*4],OFFSET NEW16H
    MOV DS:[16H*4+2],CS
    STI
    MOV DX,OFFSET START+15
    SHR DX,4
    ADD DX,10H
    MOV AL,0
    MOV AH,31H
    INT 21H
CODE ENDS
END START